version: '3.8'
services:
  adminServer:
    image: serviceapp-admin-server:0.0.1
    restart: on-failure
    ports:
      - '8081:8081'
  serviceApp:
    image: serviceapp-server:1.4.2
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - adminServer
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: service_app
      POSTGRES_PASSWORD: serviceapp14
      POSTGRES_ROOT_PASSWORD: serviceapp14
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local