package com.oblitus.serviceApp.Abstracts;

import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import lombok.AllArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Base class for every Entity in application.
 */
@AllArgsConstructor
@MappedSuperclass
public abstract class EntityBase{
    /**
     * Autogenerated UUID = Database ID
     */
    @Id
    public UUID ID;
    @CreatedDate
    protected LocalDateTime CreationDate;
    @LastModifiedDate
    protected LocalDateTime LastModificationDate;
    public Boolean ReadOnly;
    //Once Locked it can't be edited anyway
    protected Boolean Locked;

    /**
     * Constructor witch set properties:
     * @ID = Random UUID
     * @CreationDate = Now
     * @LastModyficationDate = Now
     * @ReadOnly = false
     * @Locked = false
     */
    public EntityBase() {
        ID = UUID.randomUUID();
        CreationDate = LocalDateTime.now();
        LastModificationDate = LocalDateTime.now();
        ReadOnly = false;
        Locked = false;
    }

    /**
     * Method make Entity locked
     */
    public void lockData(){
        setLastModificationDate();
        Locked = true;
    }

    public boolean isLocked(){
        return Locked;
    }
    public LocalDateTime getLastModificationDate() {
        return LastModificationDate;
    }

    public void setLastModificationDate() {
        LastModificationDate = LocalDateTime.now();
    }

    public Boolean getReadOnly() {
        return ReadOnly;
    }

    public EntityBase setReadOnly(Boolean readOnly) {
        setLastModificationDate();
        ReadOnly = readOnly;
        return this;
    }

    public UUID getID(){
        return ID;
    }

}
